#!/usr/bin/env sh

kernel="${1:-test-vm.efi}"
disk="${2:-test-luks.qcow2}"


if ! [ -f "$kernel" ]; then
  echo "The test image '$kernel' does not exist. Generate it by running 'source test-luks.env && ./build $kernel'"
  exit 1
fi

# test the current live install in qemu
sudo qemu-system-x86_64 -enable-kvm -m 2G -cpu host \
  -snapshot \
  -drive file=${disk},format=qcow2 \
  -bios /usr/share/ovmf/x64/OVMF.fd \
  -kernel "$kernel"
