#!/usr/bin/env sh

if [ -z "$ENV_GRUB_CRYPTODISK_UUID" ]; then
  echo >&2 "Root disk uuid not set: ENV_GRUB_FS_UUID is empty. Did you source .env?"
  exit 1
fi

kernel="BOOTX64.EFI"
if [ $# -gt 0 ]; then
  kernel="$1"
fi

# test the current live install in qemu

sudo qemu-system-x86_64 -enable-kvm -m 2G -cpu host \
  -snapshot \
  `#-drive file=/dev/nvme0n1p5,formar=raw,media=disk,id=drive-luks` \
  -drive file=/dev/disk/by-uuid/$ENV_GRUB_CRYPTODISK_UUID,format=raw,media=disk \
  -bios /usr/share/ovmf/x64/OVMF.fd \
  -boot order=c,menu=on \
  -kernel "$kernel"
